import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  data: [
    {
      Category: "Drama",
      Name: "everything everywhere all at once",
      Id: "1",
      img: "1.jpg",
      Date: 2022,
      Part: "2020s",
    },
    {
      Category: "Action",
      Name: "the last duel",
      Id: "2",
      img: "2.jpg",
      Date: 2021,
      Part: "2020s",
    },
    {
      Category: "Science Fiction",
      Name: "dune",
      Id: "3",
      img: "3.jpg",
      Date: 2021,
      Part: "2020s",
    },
    {
      Category: "Drama",
      Name: "drive my car",
      Id: "4",
      img: "4.jpg",
      Date: 2021,
      Part: "2020s",
    },
    {
      Category: "Drama",
      Name: "the worst person in the world",
      Id: "5",
      img: "5.jpg",
      Date: 2021,
      Part: "2020s",
    },
    {
      Category: "Drama",
      Name: "good will hunting",
      Id: "6",
      img: "6.jpg",
      Date: 1997,
      Part: "Older...",
    },
    {
      Category: "Drama",
      Name: "her",
      Id: "7",
      img: "7.jpg",
      Date: 2013,
      Part: "2010s",
    },
    {
      Category: "Drama",
      Name: "undine",
      Id: "8",
      img: "8.jpg",
      Date: 2020,
      Part: "2020s",
    },
    {
      Category: "Drama",
      Name: "parasite",
      Id: "9",
      img: "9.jpg",
      Date: 2019,
      Part: "2010s",
    },
    {
      Category: "Drama",
      Name: "gone girl",
      Id: "10",
      img: "10.jpg",
      Date: 2014,
      Part: "2010s",
    },
    {
      Category: "Drama",
      Name: "birdman",
      Id: "11",
      img: "11.jpg",
      Date: 2014,
      Part: "2010s",
    },
    {
      Category: "Drama",
      Name: "frances ha",
      Id: "12",
      img: "12.jpg",
      Date: 2012,
      Part: "2010s",
    },
    {
      Category: "Drama",
      Name: "mr nobody",
      Id: "13",
      img: "13.jpg",
      Date: 2009,
      Part: "2000s",
    },
    {
      Category: "Drama",
      Name: "the curious case of benjamin button",
      Id: "14",
      img: "14.jpg",
      Date: 2008,
      Part: "2000s",
    },
    {
      Category: "Drama",
      Name: "vicky cristina barcelona",
      Id: "15",
      img: "15.jpg",
      Date: 2008,
      Part: "2000s",
    },
    {
      Category: "Drama",
      Name: "lost in translation",
      Id: "16",
      img: "16.jpg",
      Date: 2003,
      Part: "2000s",
    },
    {
      Category: "Drama",
      Name: "memories of murder",
      Id: "17",
      img: "17.jpg",
      Date: 2003,
      Part: "2000s",
    },
    {
      Category: "Drama",
      Name: "leon the professional",
      Id: "18",
      img: "18.jpg",
      Date: 1994,
      Part: "Older...",
    },
    {
      Category: "Drama",
      Name: "cinema paradiso",
      Id: "19",
      img: "19.jpg",
      Date: 1988,
      Part: "Older...",
    },
    {
      Category: "Drama",
      Name: "one flew over the cuckoo’s nest",
      Id: "20",
      img: "20.jpg",
      Date: 1975,
      Part: "Older...",
    },
    {
      Category: "Drama",
      Name: "12 angry men",
      Id: "21",
      img: "21.jpg",
      Date: 1957,
      Part: "Older...",
    },
    {
      Category: "Drama",
      Name: "the broken landlord",
      Id: "22",
      img: "22.jpg",
      Date: 1985,
      Part: "Older...",
    },
    {
      Category: "Action",
      Name: "the brath",
      Id: "23",
      img: "23.jpg",
      Date: 2009,
      Part: "2000s",
    },
    {
      Category: "Action",
      Name: "the nice guys",
      Id: "24",
      img: "24.jpg",
      Date: 2016,
      Part: "2010s",
    },
    {
      Category: "Action",
      Name: "sicario",
      Id: "25",
      img: "25.jpg",
      Date: 2015,
      Part: "2010s",
    },
    {
      Category: "Action",
      Name: "mad max",
      Id: "26",
      img: "26.jpg",
      Date: 2015,
      Part: "2010s",
    },
    {
      Category: "Action",
      Name: "sin city",
      Id: "27",
      img: "27.jpg",
      Date: 2014,
      Part: "2010s",
    },
    {
      Category: "Action",
      Name: "snowpiercer",
      Id: "28",
      img: "28.jpg",
      Date: 2013,
      Part: "2010s",
    },
    {
      Category: "Action",
      Name: "skyfall",
      Id: "29",
      img: "29.jpg",
      Date: 2012,
      Part: "2010s",
    },
    {
      Category: "Action",
      Name: "kill bill: the whole bloody affair",
      Id: "30",
      img: "30.jpg",
      Date: 2011,
      Part: "2010s",
    },
    {
      Category: "Action",
      Name: "rocknrolla",
      Id: "31",
      img: "31.jpg",
      Date: 2008,
      Part: "Older...",
    },
    {
      Category: "Action",
      Name: "top gun  maverick",
      Id: "32",
      img: "32.jpg",
      Date: 2022,
      Part: "2020s",
    },
    {
      Category: "Action",
      Name: "children of men",
      Id: "33",
      img: "33.jpg",
      Date: 2006,
      Part: "2000s",
    },
    {
      Category: "Action",
      Name: "constantine",
      Id: "34",
      img: "34.jpg",
      Date: 2005,
      Part: "2000s",
    },
    {
      Category: "Action",
      Name: "blade",
      Id: "35",
      img: "35.jpg",
      Date: 1998,
      Part: "Older...",
    },
    {
      Category: "Action",
      Name: "kingdom of heaven",
      Id: "36",
      img: "36.jpg",
      Date: 2005,
      Part: "2000s",
    },
    {
      Category: "Action",
      Name: "battal gazi destanı",
      Id: "37",
      img: "37.jpg",
      Date: 1971,
      Part: "Older...",
    },
    {
      Category: "Action",
      Name: "braveheart",
      Id: "38",
      img: "38.jpg",
      Date: 1995,
      Part: "Older...",
    },
    {
      Category: "Action",
      Name: "heat",
      Id: "39",
      img: "39.jpg",
      Date: 1995,
      Part: "Older...",
    },
    {
      Category: "Action",
      Name: "gladiator",
      Id: "40",
      img: "40.jpg",
      Date: 1999,
      Part: "Older...",
    },
    {
      Category: "Action",
      Name: "the last samurai",
      Id: "41",
      img: "41.jpg",
      Date: 2003,
      Part: "2000s",
    },
    {
      Category: "Action",
      Name: "troy",
      Id: "42",
      img: "42.jpg",
      Date: 2004,
      Part: "2000s",
    },
    {
      Category: "Comedy",
      Name: "the mitchells vs. the machines",
      Id: "43",
      img: "43.jpg",
      Date: 2021,
      Part: "2020s",
    },
    {
      Category: "Comedy",
      Name: "aile arasında",
      Id: "44",
      img: "44.jpg",
      Date: 2017,
      Part: "2010s",
    },
    {
      Category: "Comedy",
      Name: "just go with it",
      Id: "45",
      img: "45.jpg",
      Date: 2011,
      Part: "2010s",
    },
    {
      Category: "Comedy",
      Name: "ada zombilerin düğünü",
      Id: "46",
      img: "46.jpg",
      Date: 2010,
      Part: "2010s",
    },
    {
      Category: "Comedy",
      Name: "arog",
      Id: "47",
      img: "47.jpg",
      Date: 2008,
      Part: "2000s",
    },
    {
      Category: "Comedy",
      Name: "the bucket list",
      Id: "48",
      img: "48.jpg",
      Date: 2007,
      Part: "2000s",
    },
    {
      Category: "Comedy",
      Name: "hokkabaz",
      Id: "49",
      img: "49.jpg",
      Date: 2006,
      Part: "2000s",
    },
    {
      Category: "Comedy",
      Name: "pardon",
      Id: "50",
      img: "50.jpg",
      Date: 2005,
      Part: "2000s",
    },
    {
      Category: "Comedy",
      Name: "neredesin firuze",
      Id: "51",
      img: "51.jpg",
      Date: 2004,
      Part: "2000s",
    },
    {
      Category: "Comedy",
      Name: "vizontele",
      Id: "52",
      img: "52.jpg",
      Date: 2001,
      Part: "2000s",
    },
    {
      Category: "Comedy",
      Name: "hababam sınıfı",
      Id: "53",
      img: "53.jpg",
      Date: 1975,
      Part: "Older...",
    },
    {
      Category: "Horror",
      Name: "the conjuring",
      Id: "54",
      img: "54.jpg",
      Date: 2021,
      Part: "2020s",
    },
    {
      Category: "Horror",
      Name: "midsommar",
      Id: "55",
      img: "55.jpg",
      Date: 2019,
      Part: "2010s",
    },
    {
      Category: "Horror",
      Name: "climax",
      Id: "56",
      img: "56.jpg",
      Date: 2018,
      Part: "2010s",
    },
    {
      Category: "Horror",
      Name: "a quiet place",
      Id: "57",
      img: "57.jpg",
      Date: 2018,
      Part: "2010s",
    },
    {
      Category: "Horror",
      Name: "hereditary",
      Id: "58",
      img: "58.jpg",
      Date: 2018,
      Part: "2010s",
    },
    {
      Category: "Horror",
      Name: "life",
      Id: "59",
      img: "59.jpg",
      Date: 2017,
      Part: "2010s",
    },

    {
      Category: "Horror",
      Name: "get out",
      Id: "60",
      img: "60.jpg",
      Date: 2017,
      Part: "2010s",
    },
    {
      Category: "Horror",
      Name: "the witch",
      Id: "61",
      img: "61.jpg",
      Date: 2015,
      Part: "2010s",
    },
    {
      Category: "Horror",
      Name: "the purge",
      Id: "62",
      img: "62.jpg",
      Date: 2013,
      Part: "2010s",
    },
    {
      Category: "Horror",
      Name: "the others",
      Id: "63",
      img: "63.jpg",
      Date: 2001,
      Part: "2000s",
    },
    {
      Category: "Horror",
      Name: "the shining",
      Id: "64",
      img: "64.jpg",
      Date: 1980,
      Part: "Older...",
    },
    {
      Category: "Horror",
      Name: "alien",
      Id: "65",
      img: "65.jpg",
      Date: 1979,
      Part: "Older...",
    },
    {
      Category: "Horror",
      Name: "jaws",
      Id: "66",
      img: "66.jpg",
      Date: 1975,
      Part: "Older...",
    },
    {
      Category: "Horror",
      Name: "psycho",
      Id: "67",
      img: "67.jpg",
      Date: 1960,
      Part: "Older...",
    },
    {
      Category: "Science Fiction",
      Name: "2001 a space odyssey",
      Id: "68",
      img: "68.jpg",
      Date: 1968,
      Part: "Older...",
    },
    {
      Category: "Science Fiction",
      Name: "star wars",
      Id: "69",
      img: "69.jpg",
      Date: 1977,
      Part: "Older...",
    },
    {
      Category: "Science Fiction",
      Name: "the matrix",
      Id: "70",
      img: "70.jpg",
      Date: 1999,
      Part: "Older...",
    },
    {
      Category: "Science Fiction",
      Name: "blade runner 2049",
      Id: "71",
      img: "71.jpg",
      Date: 2017,
      Part: "2010s",
    },
    {
      Category: "Science Fiction",
      Name: "the fountain",
      Id: "72",
      img: "72.jpg",
      Date: 2006,
      Part: "2000s",
    },
    {
      Category: "Science Fiction",
      Name: "arrival",
      Id: "73",
      img: "73.jpg",
      Date: 2016,
      Part: "2010s",
    },
    {
      Category: "Science Fiction",
      Name: "moon",
      Id: "74",
      img: "74.jpg",
      Date: 2009,
      Part: "2000s",
    },
    {
      Category: "Science Fiction",
      Name: "rogue one: a star wars story",
      Id: "75",
      img: "75.jpg",
      Date: 2016,
      Part: "2010s",
    },
    {
      Category: "Science Fiction",
      Name: "ex machina",
      Id: "76",
      img: "76.jpg",
      Date: 2015,
      Part: "2010s",
    },
    {
      Category: "Science Fiction",
      Name: "contact",
      Id: "77",
      img: "77.jpg",
      Date: 1997,
      Part: "Older...",
    },
    {
      Category: "Fantasy",
      Name: "fantastic beasts  the secrets of dumbledore",
      Id: "78",
      img: "78.jpg",
      Date: 2022,
      Part: "2020s",
    },
    {
      Category: "Fantasy",
      Name: "harry potter and the deathly hallows: part 2",
      Id: "79",
      img: "79.jpg",
      Date: 2011,
      Part: "2010s",
    },
    {
      Category: "Fantasy",
      Name: "the hobbit: an unexpected journey",
      Id: "80",
      img: "80.jpg",
      Date: 2012,
      Part: "2010s",
    },
    {
      Category: "Fantasy",
      Name: "the dark knight rises",
      Id: "81",
      img: "81.jpg",
      Date: 2012,
      Part: "2010s",
    },
    {
      Category: "Fantasy",
      Name: "harry potter and the deathly hallows: part 1",
      Id: "82",
      img: "82.jpg",
      Date: 2010,
      Part: "2010s",
    },
    {
      Category: "Fantasy",
      Name: "the chronicles of narnia: the voyage of the dawn treader",
      Id: "83",
      img: "83.jpg",
      Date: 2010,
      Part: "2010s",
    },
    {
      Category: "Fantasy",
      Name: "noah",
      Id: "84",
      img: "84.jpg",
      Date: 2014,
      Part: "2010s",
    },
    {
      Category: "Fantasy",
      Name: "warcraft",
      Id: "85",
      img: "85.jpg",
      Date: 2016,
      Part: "2010s",
    },
    {
      Category: "Fantasy",
      Name: "the lord of the rings: the two towers",
      Id: "86",
      img: "86.jpg",
      Date: 2002,
      Part: "2000s",
    },
    {
      Category: "Fantasy",
      Name: "harry potter and the prisoner of azkaban",
      Id: "87",
      img: "87.jpg",
      Date: 2004,
      Part: "2000s",
    },
    {
      Category: "Fantasy",
      Name: "crouching tiger, hidden dragon",
      Id: "88",
      img: "88.jpg",
      Date: 2000,
      Part: "2000s",
    },
    {
      Category: "Fantasy",
      Name: "van helsing",
      Id: "89",
      img: "89.jpg",
      Date: 2004,
      Part: "2000s",
    },
    {
      Category: "Fantasy",
      Name: "the lord of the rings: the return of the king",
      Id: "90",
      img: "90.jpg",
      Date: 2003,
      Part: "2000s",
    },
    {
      Category: "Fantasy",
      Name: "the lord of the rings: the fellowship of the ring",
      Id: "91",
      img: "91.jpg",
      Date: 2001,
      Part: "2000s",
    },
    {
      Category: "Fantasy",
      Name: "harry potter and the goblet of fire",
      Id: "92",
      img: "92.jpg",
      Date: 2005,
      Part: "2000s",
    },
    {
      Category: "Fantasy",
      Name: "jumanji",
      Id: "93",
      img: "93.jpg",
      Date: 1995,
      Part: "Older...",
    },
    {
      Category: "Fantasy",
      Name: "princess mononoke",
      Id: "94",
      img: "94.jpg",
      Date: 1997,
      Part: "Older...",
    },
    {
      Category: "Fantasy",
      Name: "ghost in the shell",
      Id: "95",
      img: "95.jpg",
      Date: 1995,
      Part: "Older...",
    },
  ],
};

export const dataSlice = createSlice({
  name: "data",
  initialState: initialState,
  reducers: {
    // addCategory: (state, { payload }) => {
    //   state.categories = [...state.categories, payload];
    // },
  },
});

export const {} = dataSlice.actions;

export default dataSlice.reducer;
